USE QLDA;

-- Bài 4.2
SELECT CONCAT(HONV, ' ', TENLOT, ' ', TENNV), YEAR(GETDATE()) - YEAR(NGSINH) AS 'TUỔI' FROM NHANVIEN;

-- Bài 4.1
SELECT CONCAT(HONV, ' ', TENLOT, ' ', TENNV) AS 'HỌ TÊN', 
       NGSINH 
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;

-- Bài 3.2
SELECT TOP(1) WITH TIES 
       NHANVIEN.PHG, 
       PHONGBAN.TENPHG, 
       PHONGBAN.TRPHG, 
       COUNT(NHANVIEN.MANV) AS 'SỐ NV', 
       REPLACE(NV.TENNV, NV.TENNV, 'Fpoly') AS 'Tên Trưởng Phòng'
FROM NHANVIEN
JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
JOIN NHANVIEN NV ON PHONGBAN.TRPHG = NV.MANV
GROUP BY NHANVIEN.PHG, TENPHG, TRPHG, NV.TENNV
ORDER BY COUNT(NHANVIEN.MANV) DESC;

-- Bài 3.1
SELECT UPPER(HONV) AS 'HỌ NV',
       LOWER(TENLOT) AS 'TÊN LÓT',
       LEFT(LOWER(TENNV), 1) + UPPER(SUBSTRING(LOWER(TENNV), 2, 1)) + RIGHT(LOWER(TENNV), 2) AS 'TÊN NV',
       SUBSTRING(DCHI, CHARINDEX(' ', DCHI) + 1, CHARINDEX(',', DCHI) - CHARINDEX(' ', DCHI) - 1) AS 'ĐỊA CHỈ',
       COUNT(THANNHAN.MA_NVIEN) AS 'COUNT(THANNHAN)'
FROM NHANVIEN
INNER JOIN THANNHAN ON NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(THANNHAN.MA_NVIEN) > 2;


-- Bài 2.2
SELECT 
	(CONCAT(HONV,' ',TENLOT,' ',TENNV)) AS 'HỌ TÊN', 
	ROUND(NHANVIEN.LUONG,2) AS 'avg(luong)' 
FROM NHANVIEN 
WHERE LUONG > ( 
	SELECT 
		AVG(LUONG) 
	FROM NHANVIEN 
	INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG 
	WHERE TENPHG LIKE N'Nghiên cứu'
)

-- Bài 2.1
SELECT 
	DEAN.TENDEAN, 
	SUM(THOIGIAN) AS 'TỔNG THỜI GIAN', 
	CEILING(SUM(THOIGIAN)) AS 'sum(thoigian)_ceiling',
	FLOOR(SUM(THOIGIAN)) AS 'sum(thoigian)_floor',
	ROUND(SUM(THOIGIAN),2) AS 'sum(thoigian)_round'
FROM PHANCONG
JOIN CONGVIEC  ON PHANCONG.MADA = CONGVIEC.MADA
JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
GROUP BY DEAN.TENDEAN;

-- Bài 1.2
SELECT 
	PHG, AVG(LUONG) AS 'avg(luong)',
	CONVERT(DECIMAL(10,2),AVG(LUONG)) AS 'avg(luong)_decimal',
	REPLACE ( CONVERT(DECIMAL(10,2), AVG(LUONG)),'.',',')  AS 'avg(luong)_decimal_replace'
FROM PHONGBAN 
JOIN NHANVIEN on PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHG;

-- Bài 1.1
SELECT 
	TENDEAN, SUM(THOIGIAN) AS 'TỔNG GIỜ', 
	CAST(SUM(THOIGIAN) AS decimal(10,2)) AS 'TỔNG GIỜ_DEC', 
	CONVERT(NVARCHAR(15), SUM(THOIGIAN)) AS  'TỔNG GIỜ VAR'
FROM PHANCONG 
JOIN CONGVIEC ON PHANCONG.MADA = CONGVIEC.MADA 
JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
GROUP BY TENDEAN;